development:
  adapter: postgresql
  encoding: unicode
  database: trip_maker_development
  pool: 5 

test:
  adapter: postgresql
  encoding: unicode
  database: trip_maker_test
  pool: 5 

production:
  adapter: postgresql
  encoding: unicode
  database: trip_maker_production
  pool: 5 


